### ISSUE TITLE
Yao::User.find is broken

### ISSUE THREAD

**Issue by hiboma** [yaocloud/yao#117]
Here is a samle code by [yrb](https://github.com/buty4649/yao-yrb)

```
yao(main):001:0> Yao::User.find('f34a8a403745488e99ae0b3d8598e611')
Traceback (most recent call last):

        ... snip  

        3: from (irb):1
        2: from /Users/hito/git/yao-yrb/vendor/bundle/ruby/2.6.0/gems/yao-0.7.0/lib/yao/resources/restfully_accessible.rb:93:in `get'
        1: from /Users/hito/git/yao-yrb/vendor/bundle/ruby/2.6.0/gems/yao-0.7.0/lib/yao/resources/user.rb:14:in `get_by_name'
ArgumentError (wrong number of arguments (given 2, expected 1))
```

Is this problem related to https://github.com/yaocloud/yao/pull/92 ?

**Comment by hiboma** [comment]
📝 This problem is related to keystone versioning with v2.0/v3,  and will be fixed in https://github.com/yaocloud/yao/pull/123.
